# Generated by Django 3.1.7 on 2021-04-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='in_stock',
            field=models.PositiveIntegerField(default=1, verbose_name='В наличии'),
        ),
    ]
