# Generated by Django 3.1.7 on 2021-03-29 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='email адрес пользователя')),
                ('birth_date', models.DateField(verbose_name='Дата рождения пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
