# Generated by Django 3.1.7 on 2021-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210420_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.ImageField(null=True),
        ),
    ]
