# Generated by Django 3.1.7 on 2021-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210324_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='goods',
        ),
        migrations.AddField(
            model_name='good',
            name='categories',
            field=models.ManyToManyField(to='main.Category'),
        ),
    ]
