# Generated by Django 3.1.7 on 2021-04-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_good_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.good',),
        ),
        migrations.AddField(
            model_name='good',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
