# Generated by Django 3.1.7 on 2021-04-01 14:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(validators=[main.models.birth_date], verbose_name='Дата рождения пользователя'),
        ),
    ]
