# Generated by Django 3.1.7 on 2021-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210324_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='manufacturer',
            field=models.CharField(default='default manufacturer', max_length=120, verbose_name='Производитель товара'),
            preserve_default=False,
        ),
    ]
