# Generated by Django 3.1.7 on 2021-03-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210324_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='tags',
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='main.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.seller'),
            preserve_default=False,
        ),
    ]
