# Generated by Django 3.1.7 on 2021-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210427_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodproxy',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Архив товаров'},
        ),
        migrations.AddField(
            model_name='good',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
