# Generated by Django 3.1.7 on 2021-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210401_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ImageField(default='static/img/default.png', upload_to='static/img'),
        ),
    ]
