# Generated by Django 3.1.7 on 2021-04-28 12:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210427_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='good',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Статус публикации'),
        ),
        migrations.RemoveField(
            model_name='good',
            name='tags',
        ),
        migrations.AddField(
            model_name='good',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None), blank=True, default='{default}', size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
