# Generated by Django 3.1.7 on 2021-04-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_good_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(default='default.png', upload_to='img'),
        ),
    ]
