# Generated by Django 3.1.7 on 2021-04-28 12:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210428_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, size=None),
        ),
    ]
