# Generated by Django 3.1.7 on 2021-04-05 15:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210401_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[main.models.birth_date], verbose_name='Дата рождения пользователя'),
        ),
    ]
