# Generated by Django 3.1.7 on 2021-04-06 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210406_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 11, 13, 53, 981105), verbose_name='Дата добавление товара в магазин'),
        ),
    ]
