# Generated by Django 3.1.7 on 2021-04-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210428_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCountView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Наименование товара')),
                ('view_count', models.ImageField(default=0, upload_to='', verbose_name='Количество просмотров')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='good',
            name='view_count',
            field=models.ImageField(default=0, upload_to='', verbose_name='Количество просмотров'),
        ),
    ]
