# Generated by Django 3.1.7 on 2021-04-06 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_good_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 8, 14, 58, 475551, tzinfo=utc), verbose_name='Дата добавление товара в магазин'),
        ),
    ]
