# Generated by Django 3.1.7 on 2021-04-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210428_1717'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodcountview',
            table='good_count_view',
        ),
    ]
