# Generated by Django 3.1.7 on 2021-04-14 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210414_1352'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='smslog',
            name='phone_confirmed',
        ),

        migrations.AddField(
            model_name='profile',
            name='phone_confirmed',
            field=models.PositiveIntegerField(default=0, verbose_name='Флаг подтверждения телефона'),
            preserve_default=False,
        ),

    ]
