# Generated by Django 3.1.7 on 2021-04-06 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210406_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавление товара в магазин'),
        ),
    ]
